USE EJ1;

-- a.
SELECT D.PROFESOR FROM D
LEFT JOIN I ON D.PROFESOR = I.PROFESOR WHERE I.MODULO IS NULL;
-- b.
SELECT PROFESOR FROM I GROUP BY PROFESOR HAVING COUNT(*) = 2;
-- c.
SELECT D.DEPARTAMENTO FROM D 
JOIN I ON D.PROFESOR = I.PROFESOR 
JOIN E ON I.MODULO = E.MODULO GROUP BY D.DEPARTAMENTO 
HAVING COUNT(DISTINCT E.CICLO) > 1;
-- d.
SELECT ALUMNO FROM M 
GROUP BY ALUMNO HAVING MIN(NOTA) > 5;
-- e.
SELECT SUM(Media) / COUNT(*) AS MediaTotal
FROM (SELECT ALUMNO, SUM(NOTA) / COUNT(*) AS Media FROM M
GROUP BY ALUMNO
HAVING SUM(NOTA >= 5) >= (COUNT(*) / 2)
) AS Subconsulta;
-- f.
SELECT MODULO FROM E WHERE CICLO = 'DAW'
ORDER BY MODULO ASC;
-- g.
SELECT PROFESOR, COUNT(*) AS Cant_Modulos FROM I
GROUP BY PROFESOR
ORDER BY Cant_Modulos DESC
LIMIT 1;